/**
 * This class was generated by BangMaple Class Generator
 * Date: 05/04/2020 17:04:00
 */
package linhnln.DTO;

import java.io.Serializable;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class BookTestDTO implements Serializable {

    public static void main(String[] args) {
//        Date d = new Date();
//        System.out.println(d);
//        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
//
//        Date today = new Date();
//
//        Date todayWithZeroTime = formatter.parse(formatter.format(today));
//        System.out.println(todayWithZeroTime);
//
//        Calendar cal = Calendar.getInstance();
//        cal.setTime(todayWithZeroTime);
//        cal.add(Calendar.DATE, 5);
//        System.out.println(cal.getTime() + "increment");
//
//        Timestamp time = new Timestamp(System.currentTimeMillis());
//        System.out.println("timestamp: " + time);
//
//        Timestamp stamp = new Timestamp(System.currentTimeMillis());
//        Date date = new Date(stamp.getTime());
//        System.out.println(date);
//        Date sqlDate = new Date(System.currentTimeMillis());
//        System.out.println(sqlDate);
//        Calendar c = Calendar.getInstance();
//        c.setTime(sqlDate);
//        c.add(Calendar.DATE, 5);
//        System.out.println(new Date(c.getTimeInMillis()));
//        List<Integer> arr = new ArrayList();
//        for (int i = 0, j = 0; i < 10; i++) {
//
//        }

        int[] arr = {1, 3, -2, 0};
        int nev = 0;
        int pos = 0;
        int zero = 0;
        int count = arr.length;
        System.out.println(count + " count ");
        for (int i = 0; i < arr.length; i++) {
            if (arr[i] > 0) {
                pos++;
                System.out.println(arr[i]);
                
            } else if (arr[i] < 0) {
                nev++;
                System.out.println(arr[i]);
            } else if (arr[i] == 0) {
                zero++;
                System.out.println(arr[i]);
            }
        }

        float nevPercent = (float) nev/count;
        float posPercent = (float) pos/count;
        float zeroPercent = (float) zero/count;
        System.out.println(nevPercent);
        System.out.println(posPercent);
        System.out.println(zeroPercent);
    }

}
